version: "3"

#  łączymy się z bazą danych za pomocą docker compose
services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: study-buddy-dev

